### ISSUE TITLE
mold-wrapper.so is missing

### ISSUE THREAD

**Issue by Guara92** [markusgod/mold-fedora-copr#1]
Hi,

I installed mold with your copr, and a library is missing when I try to run `mold -run cargo build`.
`mold: mold-wrapper.so is missing`

**Comment by markusgod** [comment]
Thanks for reporting! I'm quite amateur packager, I'll take a look.

**Comment by markusgod** [comment]
Do you have mold-wrapper.so in /lib64/mold/mold-wrapper.so ?

**Comment by Guara92** [comment]
yes 
```
➜  exa -lar /lib64/mold/mold-wrapper.so 
.rw-r--r--@ 14k root 16 dic 11:56 /lib64/mold/mold-wrapper.so
```

**Comment by markusgod** [comment]
I was able to reproduce your issue, this is possible related to https://github.com/rui314/mold/issues/160, can you try selecting linker with cargo config? 

I'm using.
```toml
[target.x86_64-unknown-linux-gnu]
linker = "clang"
rustflags = ["-Clink-arg=-fuse-ld=mold"]
```
